export const DEFAULT_DATE_FORMAT = 'yyyy-MM-dd';
export const DEFAULT_DATE_TIME_FORMAT = `${DEFAULT_DATE_FORMAT}, h:mm a`;
export const DATE_TIME_FORMAT_WITH_TIMEZONE = `${DEFAULT_DATE_TIME_FORMAT} zz`;
