export enum CheckConclusionState {
  ACTION_REQUIRED = 'ACTION_REQUIRED',
  CANCELLED = 'CANCELLED',
  FAILURE = 'FAILURE',
  NEUTRAL = 'NEUTRAL',
  SKIPPED = 'SKIPPED',
  STALE = 'STALE',
  STARTUP_FAILURE = 'STARTUP_FAILURE',
  SUCCESS = 'SUCCESS',
  TIMED_OUT = 'TIMED_OUT',
}
